language: node_js

node_js:
  - 14.16.0 
  
cache:
  directories:
    - node_modules

branches:
  only:
  - writer #源码分支名称
    
before_install:
- npm install -g hexo
    
before_script:
- git config user.name "Coldeye"
- git config user.email "948283368@qq.com"
- sed -i'' "s~https://github.com/coldeye2020/coldeye2020.github.io.git~https://${GH_TOKEN}@github.com/<yourname>/<reopname>.git~" _config.yml

install:
- npm install

script:
- hexo clean
- hexo generate

after_success:
- hexo deploy