sudo: false
language: node_js
node_js:
  - 14.16.0 
cache:
  directories:
    - node_modules
branches:
  only:
    - writer # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: writer
  local-dir: public
  target_branch: main
